---
title: "Reproduzierbarkeit"
date: today
---

# FAIR für Forschungssoftware

Um Forschungsergebnisse und Code transparenter und nachvollziehbarer zu machen, gibt es die sogenannten FAIR-Prinzipien (Findable, Accessible, Interoperable, Reusable). Hier ist erklärt, was diese bedeuten und wie wir sie in RStudio umsetzen:

1.  **Findable**: Software sollte für Mensch und Maschiene leicht auffindbar sein. Ausserdem sollte Software einen klar zuordbaren Identifer besitzen (beispielsweise einen Digital Object Identifier, DOI).

    Beispiel: Im Rahmen von Forschungszwecken kann man jegliche Dateien wie beispielsweise ein R-Skript auf [Zenodo](https://zenodo.org/) hochladen und mit einer entsprechenden DOI versehen. In Zukunft ist das Skript dann über die entsprechende DOI für Mensch und Maschiene klar zuordbar.

2.  **Accessible**: Software sollte für Menschen und Maschinen zugänglich sein, idealerweise über eine öffentliche Lizenz. Metadaten zur Software sollten auch dann noch zugänglich sein wenn es die Software nicht mehr ist.

    Beispiel: R und RStudio sind beide *Open source* Software. Der Quellcode hinter der Programmiersprache R und hinter der Enwicklungsumbegung von RStudio ist einsehbar, darf verändert und weiter verbreitet werden.

3.  **Interoperable**: Software sollte mit anderen Softwareprodukten und Daten kompatibel sein, um die Zusammenarbeit und den Austausch von Informationen zu erleichtern. Dies kann durch die Verwendung von offenen Standards und Schnittstellen erreicht werden.

    Beispiel: R und RStudio unterstützen eine Vielzahl von Paketen, die von der Community entwickelt wurden. Diese Pakete ermöglichen es beispielsweise Daten aus verschiedenen Quellen zu importieren (Excel-Dateien, JSON-Dateien, Dateien direkt von Websiten etc.).

4.  **Reusable**: Software sollte so gestaltet sein, dass sie von anderen Forschern leicht wiederverwendet werden kann. Hierzu gehört, dass sie verständlich dokumentiert ist, auf ihr aufbauend Modifizierungen vorgenommen werden können oder sie in eine andere Software integrierbar ist.

    Beispiel: In Quarto geschriebene Dateien enden auf .qmd und sind auch von anderen Programmen lessbar. Packages in R haben, sofern sie auf der offiziellen Website von [CRAN](https://cran.rstudio.com/) gelistet sind, immer auch eine ausführliche Dokumentation.
